# Generated by Django 4.1.2 on 2022-10-15 03:01

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Poner nombre del actor, 'Nombre Apellido'", max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Poner nombre del director', max_length=64)),
                ('surname', models.CharField(help_text='Poner nombre del director', max_length=64)),
                ('birth', models.DateField(blank=True, null=True)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Pone el nombre de la película', max_length=64)),
                ('age', models.DateField(blank=True, help_text='Pon la fecha de lanzamiento de la película', null=True)),
                ('genero', models.CharField(help_text='Pon el género de la película', max_length=50)),
                ('summary', models.TextField(help_text='Pon un resumen de la película')),
                ('cast', models.ManyToManyField(to='cine.cast')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cine.director')),
            ],
        ),
    ]
